AspNetCore.VueJs/Models/CharacterResponse.cs
namespace AspNetCore.VueJs.Models
{
    public class CharacterResponse
    {
        public string Url { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Culture { get; set; }
        public string Born { get; set; }
        public string Died { get; set; }
        public string[] Titles { get; set; }
        public string[] Aliases { get; set; }
        public string Father { get; set; }
        public string Mother { get; set; }
        public string Spouse { get; set; }
        public string[] Allegiances { get; set; }
        public string[] Books { get; set; }
        public string[] PovBooks { get; set; }
        public string[] TvSeries { get; set; }
        public string[] PlayedBy { get; set; }
    }
}

AspNetCore.VueJs/Models/ErrorViewModel.cs
using System;

namespace AspNetCore.VueJs.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AspNetCore.VueJs/Controllers/IDontNeedTypeScriptController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetCore.VueJs.Controllers
{
    public class IDontNeedTypeScriptController : Controller
    {
        /// <summary>
        /// SPA entry point
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }
    }
}

AspNetCore.VueJs/Controllers/IceAndFireController.cs
using AspNetCore.VueJs.Constants;
using AspNetCore.VueJs.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;
using System.Threading.Tasks;

namespace AspNetCore.VueJs.Controllers
{
    [Route(ApiRoutes.IceAndFire.BaseRoute)]
    public class IceAndFireController : Controller
    {
        private const string ApiOfIceAndFireCharactersUrl = "https://anapioficeandfire.com/api/characters";

        private readonly HttpClient _httpClient;

        public IceAndFireController(IHttpClientFactory httpClientFactory)
        {
            _httpClient = httpClientFactory.CreateClient();
        }

        /// <summary>
        /// SPA entry point
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet(ApiRoutes.IceAndFire.CharactersById)]
        public async Task<IActionResult> GetCharacterAsync([FromRoute] int id)
        {
            if (id == default(int))
                return BadRequest();

            CharacterResponse response;
            var apiResponse = await _httpClient.GetAsync($"{ApiOfIceAndFireCharactersUrl}/{id}").ConfigureAwait(false);

            response = JsonConvert.DeserializeObject<CharacterResponse>(await apiResponse.Content.ReadAsStringAsync().ConfigureAwait(false));

            return Ok(response);
        }
    }
}

AspNetCore.VueJs/Controllers/TemplateController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetCore.VueJs.Controllers
{
    public class TemplateController : Controller
    {
        /// <summary>
        /// SPA entry point
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {
            return View();
        }
    }
}

AspNetCore.VueJs/Views/IDontNeedTypeScript/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@section scripts{

    <environment names="Development,Production,Staging">
        <script src="~/dist/js/idontneedtypescript/bundle.js" asp-append-version="true"></script>
    </environment>

}

<div id="app">

</div>

AspNetCore.VueJs/Views/IceAndFire/Index.cshtml
@{
    ViewData["Title"] = "Ice and fire";
}

@section styles{

}

@section scripts{

    <environment names="Development,Production,Staging">
        <script src="~/dist/js/iceandfire/bundle.js" asp-append-version="true"></script>
    </environment>

}

<div id="app">

</div>

AspNetCore.VueJs/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>AspNetCore.Vue.js</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/dist/css/vendor/main.css" asp-append-version="true" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/dist/css/vendor/main.css" asp-append-version="true" />
    </environment>

    @RenderSection("Styles", required: false)
</head>
<body>

    @await Html.PartialAsync("_Navigation")

    <div>
        @RenderBody()
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>

AspNetCore.VueJs/Views/Shared/_Navigation.cshtml
<nav class="navbar is-white shadow">
    <div class="container">
        <div class="navbar-brand">
            <a class="navbar-item brand-text"
               href="../">
                Vue.js Template
            </a>
            <div class="navbar-burger burger"
                 data-target="navMenu">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div id="navMenu"
             class="navbar-menu">
            <div class="navbar-start">
                <a asp-controller="Template"
                   asp-action="Index" class="navbar-item">Template</a>
                <a asp-controller="IDontNeedTypeScript"
                   asp-action="Index" class="navbar-item">No TypeScript</a>
                <a asp-controller="IceAndFire"
                   asp-action="Index" class="navbar-item">Api of Ice and fire</a>
            </div>

        </div>
    </div>
</nav>

AspNetCore.VueJs/Views/Template/Index.cshtml
@{
    ViewData["Title"] = "Template";
}

@section styles{

<environment names="Development,Production,Staging">
    <link rel="stylesheet" href="~/dist/css/template/main.css" asp-append-version="true" />
</environment>

}

@section scripts{

    <environment names="Development,Production,Staging">
        <script src="~/dist/js/template/bundle.js" asp-append-version="true"></script>
    </environment>

}

<div id="app">

</div>